{
  "runOn": [
    {
      "minServerVersion": "4.0",
      "topology": [
        "single",
        "replicaset"
      ]
    },
    {
      "minServerVersion": "4.1.7",
      "topology": [
        "sharded"
      ]
    }
  ],
  "database_name": "retryable-reads-tests",
  "collection_name": "coll",
  "data": [
    {
      "_id": 1,
      "x": 11
    },
    {
      "_id": 2,
      "x": 22
    },
    {
      "_id": 3,
      "x": 33
    }
  ],
  "tests": [
    {
      "description": "Aggregate succeeds after InterruptedAtShutdown",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 11600
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "result": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after InterruptedDueToReplStateChange",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 11602
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "result": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after NotMaster",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 10107
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "result": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after NotMasterNoSlaveOk",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 13435
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "result": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after NotMasterOrSecondary",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 13436
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "result": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after PrimarySteppedDown",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 189
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "result": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after ShutdownInProgress",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 91
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "result": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after HostNotFound",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 7
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "result": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after HostUnreachable",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 6
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "result": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after NetworkTimeout",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 89
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "result": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after SocketException",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 9001
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "result": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            }
          ]
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate fails after two NotMaster errors",
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 2
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 10107
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "error": true
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate fails after NotMaster when retryReads is false",
      "clientOptions": {
        "retryReads": false
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 10107
        }
      },
      "operations": [
        {
          "name": "aggregate",
          "object": "collection",
          "arguments": {
            "pipeline": [
              {
                "$match": {
                  "_id": {
                    "$gt": 1
                  }
                }
              },
              {
                "$sort": {
                  "x": 1
                }
              }
            ]
          },
          "error": true
        }
      ],
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    }
  ]
}
